name: G3D-Editor (Linux)

on:
  push:
    paths:
      - 'src/**'
      - 'build_linux_x64.xml'
  pull_request:
    paths:
      - 'src/**'
      - 'build_linux_x64.xml'
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Install Apache Ant
      run: sudo apt-get update && sudo apt-get install -y ant

    - name: Build with Ant
      run: ant -f build_linux_x64.xml dist-targz

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: G3DEditor-linux
        path: build/linux_x64/G3DEditor_linux_x64_*.tar.gz
