name: G3D-Editor (Linux)

on:
  push:
    paths:
      - 'src/**'
      - 'build_linux_x64.xml'
  pull_request:
    paths:
      - 'src/**'
      - 'build_linux_x64.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Install Apache Ant
      run: sudo apt-get update && sudo apt-get install -y ant

    - name: Build with Ant
      run: ant -f build_linux_x64.xml dist-targz

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: G3DEditor-linux
        path: build/linux_x64/G3DEditor_linux_x64_*.tar.gz

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: G3DEditor Linux v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_BUILD }}

    - name: Upload release artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/linux_x64/G3DEditor_linux_x64_*.tar.gz
        asset_name: G3DEditor_linux_x64_${{ github.run_number }}.tar.gz
        asset_content_type: application/gzip
