name: G3D-Editor (Windows)

on:
  push:
    paths:
      - 'src/**'
      - 'build_win_x64.xml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'

    - name: Install Apache Ant
      run: choco install ant -y

    - name: Build with Ant
      run: ant -f build_win_x64.xml dist-zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: G3DEditor-windows
        path: build/win_x64/G3DEditor_win_x64_*.zip

    - name: Install GitHub CLI
      run: choco install gh -y

    - name: Create or update GitHub Release
      run: |
        SET TAG_NAME=v1.0

        gh release view %TAG_NAME% >nul 2>&1
        IF %ERRORLEVEL% EQU 0 (
          echo "Release exists, updating assets..."
          gh release upload %TAG_NAME% build/win_x64/G3DEditor_win_x64_*.zip --clobber
        ) ELSE (
          echo "Release does not exist, creating..."
          gh release create %TAG_NAME% build/win_x64/G3DEditor_win_x64_*.zip --title "G3DEditor Windows %TAG_NAME%" --notes "Build gerado automaticamente"
        )
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_BUILD }}
